spring:
  mail:
    configs:
      qq:
        host: smtp.qq.com
        port: 465
        username: xxxxxxxxx@qq.com
        password: xxxxxxxxxxxxx
        properties:
          mail:
            smtp:
              ssl:
                enable: true
        suffix: "@qq.com"
      gmail:
        host: smtp.gmail.com
        port: 465
        username: xxxxxx@gmail.com
        password: xxxxxxxxxx
        properties:
          mail:
            smtp:
              ssl:
                enable: true
        suffix: "@gmail.com"

